export default {
	name: 'Axel Deneu',
	initials: 'AD',
	title: 'Lead Web Developer',
	url: 'https://aden.solutions',
	img: 'https://avatars.githubusercontent.com/u/22771331?v=4',
	location: 'Montval-sur-Loir, France',
	locationLink: 'https://www.google.com/maps/place/montval-sur-loir',
	avatarUrl: 'https://avatars.githubusercontent.com/u/22771331?v=4',
	skills: [
		'PHP',
		'Laravel',
		'Inertia.js',
		'Symfony',
		'TypeScript',
		'Node.js',
		'Svelte',
		'SvelteKit',
		'Vue.js',
		'React',
		'TailwindCSS',
		'SASS',
		'LESS',
		'PostgreSQL',
		'MySQL',
		'Docker',
		'Git',
		'REST API',
		'GraphQL',
		'Redis',
		'Nginx',
		'Linux'
	],
	greetings: 'Greetings',
	about: 'About',
	description: 'Description',
	summary: 'Summary',
	seo: {
		title: 'Axel Deneu - Fullstack Web Developer',
		description: 'seo.description',
		keywords: 'seo.keywords',
		author: 'Axel Deneu',
		image: 'https://avatars.githubusercontent.com/u/22771331?v=4',
		imageAlt: 'Axel Deneu - Fullstack Web Developer',
		twitterCreator: '@axeldeneu',
		locale: 'en_US'
	},
	social: {
		github: 'https://github.com/AxelDeneu',
		linkedin: 'https://www.linkedin.com/in/adeneu/',
		twitter: 'https://twitter.com/axeldeneu',
		email: 'hello@aden.solutions',
		malt: 'https://www.malt.fr/profile/axeldeneu'
	}
};
